print("data/raw/")
print("├── train/")
print("│   ├── CNV/")
print("│   ├── DME/")
print("│   ├── DRUSEN/")
print("│   └── NORMAL/")
print("├── val/")
print("│   ├── CNV/")
print("│   ├── DME/")
print("│   ├── DRUSEN/")
print("│   └── NORMAL/")
print("└── test/")
print("    ├── CNV/")
print("    ├── DME/")
print("    ├── DRUSEN/")
print("    └── NORMAL/")